### ISSUE TITLE
Unhandled entity metadata with mods on the server

### ISSUE THREAD

**Issue by phit** [PaperMC/Waterfall#136]
I tested this with

WaterFall Build108
HexaCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:6e70b90:142
BungeeCord Build1233 + SpongePls

To test, have a 1.11.2 forge server with Jurassicraft and spawn any of its mobs (dinosaurs)
client gets moved to fallback server, you can't login either until the mob is removed

console error's https://gist.github.com/phit/2aa7d57d12e28cc4c246999ef4fd0424

I have temporary solution in place right now https://github.com/Stonebound/BungeeCord/commit/2d1ad7d77cc70b2073b7bd92b608edfd5066c8d6 .
It would be great to handle this better, if a metaid isn't known to Bungee since it was added by a mod. I'm sure this will be a bigger issue once more modded servers move to 1.11 and Jurassicraft is probably not the only mod adding it's own meta ids. Note this wasn't an issue in previous versions since this case was added only for 1.11 and later https://github.com/SpigotMC/BungeeCord/commit/6104354fa1a87a8a09d852ef8ec388611a9b51f1

**Comment by jamierocks** [comment]
Any chance you could give https://github.com/WaterfallMC/Waterfall/commit/1d37e88f540b17ac14019fdbc46d994de0dee24e a test?

**Comment by phit** [comment]
I just realized there is two separate issues here, which also explains the two different stacktraces in the Gist of my initial post.

When using only Jurassicraft on a Test server it uses Meta ID 13 which throws this stacktrace since it tries to apply [this](https://github.com/SpigotMC/BungeeCord/blob/16d261553c1a648ce38101bda19b7166d1ca5a41/proxy/src/main/java/net/md_5/bungee/entitymap/EntityMap.java#L187). I guess MetaID 13 isn't actually used in Vanilla, so it gets taken by a mod? Which wasn't fixed by https://github.com/WaterfallMC/Waterfall/commit/1d37e88f540b17ac14019fdbc46d994de0dee24e since it obviously didn't change anything for 13

```
19:49:08 [SEVERE] [/127.0.0.1:58014|phit] <-> DownstreamBridge <-> [hub] - encountered exception
java.lang.RuntimeException: java.io.IOException: TAG_End found without a TAG_Compound/TAG_List tag preceding it.
    at com.google.common.base.Throwables.propagate(Throwables.java:160)
    at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:193)
    at net.md_5.bungee.entitymap.EntityMap_1_11.rewriteClientbound(EntityMap_1_11.java:152)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:120)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: TAG_End found without a TAG_Compound/TAG_List tag preceding it.
    at com.flowpowered.nbt.stream.NBTInputStream.readTagPayload(NBTInputStream.java:144)
    at com.flowpowered.nbt.stream.NBTInputStream.readTag(NBTInputStream.java:127)
    at com.flowpowered.nbt.stream.NBTInputStream.readTag(NBTInputStream.java:103)
    at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:190)
    ... 36 more
```

Then when I run our full modpack something else must be using MetaID 13 and 14, so Jurassicraft uses MetaID 15 which before threw [this expection](https://gist.github.com/phit/2aa7d57d12e28cc4c246999ef4fd0424#file-hexagon-bungee), with the patch added in https://github.com/WaterfallMC/Waterfall/commit/1d37e88f540b17ac14019fdbc46d994de0dee24e you just time out..

```
20:00:12 [INFO] [phit|/127.0.0.1:58749] <-> ServerConnector [hub] has connected
20:00:12 [INFO] [phit|/127.0.0.1:58749] <-> ServerConnector [hub] has disconnected
20:00:36 [WARNING] [/127.0.0.1:58749|phit] -> UpstreamBridge - read timed out
20:00:36 [INFO] [phit] disconnected with: ReadTimeoutException : null
20:00:36 [INFO] [/127.0.0.1:58749|phit] -> UpstreamBridge has disconnected
```

**Comment by DaMatrix** [comment]
Can confirm this is still an issue, don't want to necro an old thread but it's something that needs to be fixed.

**Comment by Lachney** [comment]
I'm getting this I believe as well with Waterfall. Here is my own log. This is happening when using a special tool to make blocks float... gravitate from Aether.
https://gist.github.com/Lachney/ee696cb3d2704e638ead8b1b253f16c1

**Comment by phit** [comment]
well then, this is still an issue

**Comment by phit** [comment]
nope

**Comment by DaMatrix** [comment]
since my last comment i've been running a pretty big (~180 mods) pack behind waterfall and haven't been getting these errors any more, so i would say this is most likely fixed

**Comment by phit** [comment]
the offending code is still there, so no this is not fixed, you probably just had no mods installed that can trigger it
a very small minority of mods use this..

**Comment by electronicboy** [comment]
Any mod which uses custom entity metadata formats outside of what is added by mojang will throw an exception while processing data, the problem here being that in order to support rewriting metadata as needed by bungeecord, we need to know the format of the metadata, which isn't possible for bungee.

I was playing with removing the entity rewrites a few months ago but it did have an issue remaining which I didn't get the time to look into

**Comment by BrainStone** [comment]
I'd like to chime in here too and point out that it's even prevent us from joining the server at the moment.
Waterfall just logs this:
```
 [20:12:22 ERROR]: [/185.17.206.10:18941|Bone44] <-> DownstreamBridge <-> [modded] - encountered exception
java.lang.IllegalArgumentException: Unknown meta type 17
at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:235) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:128) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at net.md_5.bungee.entitymap.EntityMap_1_12_1.rewriteClientbound(EntityMap_1_12_1.java:152) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at net.md_5.bungee.entitymap.EntityMap.rewriteClientbound(EntityMap.java:94) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:122) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9e5bc39:221]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

A new world fixes that. Should've made a backup to figure out which mod causes the issues.  
Welp too late for that...

**Comment by Bucky420** [comment]
i can name about 4 -5 mods that still do this :)

**Comment by zwamdurkel** [comment]
I can confirm that this is still an issue

**Comment by Keaton1188** [comment]
Also having this issue since updating Revelations from .5 to .6

**Comment by krisjenner** [comment]
my waterfall.yml if this helps https://gist.github.com/krisjenner/06e9ce002d4af4792a56647bd86f16a2

**Comment by mikroskeem** [comment]
I believe that Waterfall maintainers know what causes this and this is quite common with mods utilizing custom entity metadata. There's actually no need to confirm it on your side, as with design what BungeeCord (where Waterfall derives its code) has, it cannot be worked around easily.

**Comment by th2m1** [comment]
We have this issue on revelation 2.6.0, latest enigmatica2 , atm3-remix modpacks.

**Comment by Keaton1188** [comment]
FTB Updated Dw20 1.12 to the new version (2.4.0) and it is now a problem on this server.

Wondering if there is any update on this or not? Its not a massive issue as we can go back a version.

**Comment by alicheek** [comment]
DW20 1.12.2 updated version of 2.4.0 same meta ID as Revelations modpack issue 👍 

`[00:05:06] [Netty Worker IO Thread #0/INFO]: [Insultron|/109.149.78.140:56443] <-> ServerConnector [DW20] has connected
[00:05:06] [Netty Worker IO Thread #0/INFO]: [Insultron|/109.149.78.140:56443] <-> ServerConnector [DW20] has disconnected
[00:05:06] [Netty Worker IO Thread #0/INFO]: [Insultron|/109.149.78.140:56443] <-> ServerConnector [Lobby] has connected
[00:05:19] [Netty Worker IO Thread #12/ERROR]: [/94.239.122.246:59128|Viooo] <-> DownstreamBridge <-> [DW20New] - encountered exception
java.lang.IllegalArgumentException: Unknown meta type 14
	at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:240) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:133) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at net.md_5.bungee.entitymap.EntityMap_1_12_1.rewriteClientbound(EntityMap_1_12_1.java:152) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at net.md_5.bungee.entitymap.EntityMap.rewriteClientbound(EntityMap.java:99) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:122) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[Travertine.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:2900c0b:unknown]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]`

**Comment by electronicboy** [comment]
I'll try and get to it this weekend™

**Comment by alicheek** [comment]
@electronicboy Thank you, do appreciate it. Will really help a lot if we can get around this issue.

**Comment by kamcio96** [comment]
I can't find BungeeCord PR. It removes entity id rewrite, so possibly can fix this.

**Comment by kamcio96** [comment]
Removing entity id rewrite can fix this. https://github.com/PaperMC/Waterfall/pull/309 Can't find PR for BungeeCord

**Comment by Keaton1188** [comment]
Sounds good, thanks Electronicboy.

**Comment by Adam3055** [comment]
Glad this is hopefully going to get fixed! 

@electronicboy Hate to ping but did you have a chance of looking at it??

**Comment by Keaton1188** [comment]
Is that a fix I see @electronicboy ^^ :DD

Just waiting for it to be uploaded to Jenkins?

**Comment by electronicboy** [comment]
Code is currently on my own fork as a branch, (see above this comment), I'll try and maintain a build here if any changes are made: https://keybase.pub/electronicboy/builds/waterfall/WaterfallEntityDismap.jar

I've added a configuration setting inside of waterfall.yml, `disable_entity_metadata_rewrite` which you'll need to flip to test, while there shouldn't be any changes with this unflipped, I'd rather capture any issues head-on, which is where you guys come in;

I've tested with one of the FTB packs, forestry has an entity which can be summoned with the command which will send unsupported metadata for an obvious test, but I'm more concerned with any issues around plugins and server switching

**Comment by Keaton1188** [comment]
Sounds good @electronicboy 

So throw that jar in with the others and basically have a test with it. 

Last server we had this issue on was Revelations and Dw20, so we will update them to the newest version again and give it a test.

**Comment by Keaton1188** [comment]
Just so we are clear, that jar file needs to go in modules??

![untitled](https://user-images.githubusercontent.com/24898745/51204371-5d23dc80-18fb-11e9-9187-c5ee09bac207.png)

**Comment by electronicboy** [comment]
No, it's a build of waterfall with the patch applied, you need to replace waterfall itself

**Comment by Keaton1188** [comment]
Ah my bad, thankyou

**Comment by alicheek** [comment]
@electronicboy  Only issue is we previously used travertine for 1.7.10 at this current point does Waterfall support this?

**Comment by electronicboy** [comment]
Was having issues with Keybase on my laptop, but pushed an updated build which fixes an issue with Boss bars

**Comment by alicheek** [comment]
@electronicboy  any chance you would know when this should be merged to the main build as travertine have advised that this would not be complimented until then, our issue is we have 1.7.10 servers too 1.12.2

**Comment by 5aji** [comment]
This fix seems to work. We haven't noticed any problems yet. We are running SpongeForge FTB Revalations 2.7.0. I'll let you know if we encounter any problems. Thanks for all your hard work!

**Comment by electronicboy** [comment]
The changes in the above build have been merged into master, The credit for this patch mostly boils down to the efforts of the technical Minecraft development community, and I'm glad that we have a platform such as Waterfall were we can bring these changes in

I'll likely be merging into Travertine this weekend sometime, need to be able to sit down long enough at my desk to get it in and ensure that it works fine over there

**Comment by Keaton1188** [comment]
Sounds good 

Thankyou  @electronicboy

**Comment by Adam3055** [comment]
Thanks @electronicboy 

This will sort out problems once its updated on Travertine :D

**Comment by Sharkske** [comment]
i tried this temp fix but it seems to break things with my 1.7.10 servers ozone 2, FTB infinity, ect. it crashes the clients when falling back to the fallback server with client error 

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.network.NetHandlerPlayClient.func_147247_a(NetHandlerPlayClient.java:1552)
	at net.minecraft.network.play.server.S3EPacketTeams.func_148833_a(SourceFile:100)
	at net.minecraft.network.play.server.S3EPacketTeams.func_148833_a(SourceFile:12)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
